services:
  db:
    image: postgres:15-alpine
    container_name: eventic-db
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network
    env_file:
      - ../../src/.env

  backend:
    container_name: eventic-backend
    build:
      context: ../../
      dockerfile: utils/Dockerfile
    volumes:
      - ../..:/opt/services/eventic-backend
    env_file:
      - ../../src/.env
    ports:
      - "8000:8000"
    command: "bash /opt/services/eventic-backend/utils/entrypoints/start_back.sh"
    networks:
      - main_network
      - nginx_network
    depends_on:
      - db

volumes:
  postgres_storage: {}

networks:
  main_network:
    driver: bridge
